### ISSUE TITLE
Unable to get package

### ISSUE THREAD

**Issue by mdollemore** [webdevops/azure-metrics-exporter#11]
Trying to go get package  and get the following errors, other packages work fine, am I missing something?;-

go get -u github.com/webdevops/azure-metrics-exporter
package google.golang.org/protobuf/encoding/prototext: unrecognized import path "google.golang.org/protobuf/encoding/prototext": https fetch: Get "https://google.golang.org/protobuf/encoding/prototext?go-get=1": proxyconnect tcp: tls: first record does not look like a TLS handshake
package google.golang.org/protobuf/encoding/protowire: unrecognized import path "google.golang.org/protobuf/encoding/protowire": https fetch: Get "https://google.golang.org/protobuf/encoding/protowire?go-get=1": proxyconnect tcp: tls: first record does not look like a TLS handshake
package google.golang.org/protobuf/proto: unrecognized import path "google.golang.org/protobuf/proto": https fetch: Get "https://google.golang.org/protobuf/proto?go-get=1": proxyconnect tcp: tls: first record does not look like a TLS handshake
package google.golang.org/protobuf/reflect/protodesc: unrecognized import path "google.golang.org/protobuf/reflect/protodesc": https fetch: Get "https://google.golang.org/protobuf/reflect/protodesc?go-get=1": proxyconnect tcp: tls: first record does not look like a TLS handshake
package google.golang.org/protobuf/reflect/protoreflect: unrecognized import path "google.golang.org/protobuf/reflect/protoreflect": https fetch: Get "https://google.golang.org/protobuf/reflect/protoreflect?go-get=1": proxyconnect tcp: tls: first record does not look like a TLS handshake
package google.golang.org/protobuf/reflect/protoregistry: unrecognized import path "google.golang.org/protobuf/reflect/protoregistry": https fetch: Get "https://google.golang.org/protobuf/reflect/protoregistry?go-get=1": proxyconnect tcp: tls: first record does not look like a TLS handshake
package google.golang.org/protobuf/runtime/protoiface: unrecognized import path "google.golang.org/protobuf/runtime/protoiface": https fetch: Get "https://google.golang.org/protobuf/runtime/protoiface?go-get=1": proxyconnect tcp: tls: first record does not look like a TLS handshake
package google.golang.org/protobuf/runtime/protoimpl: unrecognized import path "google.golang.org/protobuf/runtime/protoimpl": https fetch: Get "https://google.golang.org/protobuf/runtime/protoimpl?go-get=1": proxyconnect tcp: tls: first record does not look like a TLS handshake
package google.golang.org/protobuf/types/known/anypb: unrecognized import path "google.golang.org/protobuf/types/known/anypb": https fetch: Get "https://google.golang.org/protobuf/types/known/anypb?go-get=1": proxyconnect tcp: tls: first record does not look like a TLS handshake
package google.golang.org/protobuf/types/known/durationpb: unrecognized import path "google.golang.org/protobuf/types/known/durationpb": https fetch: Get "https://google.golang.org/protobuf/types/known/durationpb?go-get=1": proxyconnect tcp: tls: first record does not look like a TLS handshake
package google.golang.org/protobuf/types/known/timestamppb: unrecognized import path "google.golang.org/protobuf/types/known/timestamppb": https fetch: Get "https://google.golang.org/protobuf/types/known/timestamppb?go-get=1": proxyconnect tcp: tls: first record does not look like a TLS handshake

**Comment by mblaschke** [comment]
hm.. are you using a proxy? According to the error messages you have a problem tls handshake problem connecting to google.golang.org.

Why not just use the docker image? any issues with that?

**Comment by mdollemore** [comment]
Yes a proxy is involved, but not maintained by me, I will take it up with
our network team and see if they can fix it. Unfortunately docker is not an
option at present.

Thanks for responding.

Mark

**Comment by mblaschke** [comment]
closing, hope you found a solution.
btw: in docker it's a static binary so you could also extract the binary from the docker image. it's one single binary file.
