### ISSUE TITLE
Runtime error crash

### ISSUE THREAD

**Issue by mdollemore** [webdevops/azure-metrics-exporter#15]
Hi there,

I am seeing the following runtime error/crash;-

INFO[0000] starting azure-metrics-exporter v<unknown> (<unknown>; go1.15.5; by webdevops.io)
INFO[0000] {"Logger":{"Debug":false,"Verbose":false,"LogJson":false},"Azure":{"Environment":"AZUREPUBLICCLOUD","AdResourceUrl":null,"ServiceDiscovery":{"CacheDuration":1800000000000}},"Metrics":{"ResourceIdLowercase":false,"Template":"{name}"},"Prober":{"ConcurrencySubscription":5,"ConcurrencySubscriptionResource":10,"Cache":false},"ServerBind":":8080"}
INFO[0000] init Azure connection
INFO[0000] starting http server on :8080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x9688fc]

goroutine 1011 [running]:
github.com/webdevops/azure-metrics-exporter/metrics.(*MetricProber).FetchMetricsFromTarget(0xc00016c000, 0xc00014c630, 0xc0003046e0, 0x98, 0xc0001a90f0, 0x1, 0x1, 0xc00000f8c0, 0x2, 0x2, ...)
        /omd/sites/stage/go/src/github.com/webdevops/azure-metrics-exporter/metrics/insights.go:57 +0x45c
github.com/webdevops/azure-metrics-exporter/metrics.(*MetricProber).collectMetricsFromTargets.func1.1.1(0xc000532ae0, 0xc00016c000, 0xc00014c630, 0xc0001a4600, 0xc0003046e0, 0x98, 0xc0001a90f0, 0x1, 0x1, 0xc00000f8c0, ...)
        /omd/sites/stage/go/src/github.com/webdevops/azure-metrics-exporter/metrics/prober.go:186 +0xb8
created by github.com/webdevops/azure-metrics-exporter/metrics.(*MetricProber).collectMetricsFromTargets.func1.1
        /omd/sites/stage/go/src/github.com/webdevops/azure-metrics-exporter/metrics/prober.go:184 +0x27f

http service works fine for a while and services requests returning metrics as expected, but after anything between 2 hours and 12 hours I get the above crash.

Any help would be appreciated

Thanks

Mark

**Comment by mblaschke** [comment]
fixed by https://github.com/webdevops/azure-metrics-exporter/issues/12#issuecomment-907360390
