### ISSUE TITLE
Add metrics to count how many http request failures is happening towards azure

### ISSUE THREAD

**Issue by NissesSenap** [webdevops/azure-metrics-exporter#17]
First of all thanks for a great project.
One thing that I'm missing is a counter for how many requests that is actually returns a 200/400 etc when talking to Azure.

It would probably be good to add a count for how many requests that you have performed for the last hour, to give your users a feeling on how long it's left until the API request limit: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/request-limits-and-throttling

If this is something that you think is a good idea, I'm willing to create a PR for this.

**Comment by mblaschke** [comment]
You mean requests from the exporter?

**Comment by NissesSenap** [comment]
Yes precisely

**Comment by mblaschke** [comment]
i'm thinking about a solution for all azure exporters
something like:

```
azurerm_apicalls{endpoint="management.azure.com",status="200"} xxx
azurerm_apicalls{endpoint="management.azure.com",status="501"} xxx
azurerm_apicalls{endpoint="management.azure.com",status="401"} xxx
```

not sure who easy it would be to integrate also latency

**Comment by mblaschke** [comment]
found a possible solution with HistogramVec: 

```
azureapi_request_bucket{statusCode="200",le="0.005"} 1
azureapi_request_bucket{statusCode="200",le="0.01"} 1
azureapi_request_bucket{statusCode="200",le="0.025"} 1
azureapi_request_bucket{statusCode="200",le="0.05"} 1
azureapi_request_bucket{statusCode="200",le="0.1"} 1
azureapi_request_bucket{statusCode="200",le="0.25"} 1
azureapi_request_bucket{statusCode="200",le="0.5"} 1
azureapi_request_bucket{statusCode="200",le="1"} 3
azureapi_request_bucket{statusCode="200",le="2.5"} 4
azureapi_request_bucket{statusCode="200",le="5"} 4
azureapi_request_bucket{statusCode="200",le="10"} 4
azureapi_request_bucket{statusCode="200",le="+Inf"} 4
azureapi_request_sum{statusCode="200"} 2.926089
azureapi_request_count{statusCode="200"} 4
```

**Comment by NissesSenap** [comment]
Looks like a great option.

**Comment by mblaschke** [comment]
```
# HELP azurerm_api_ratelimit AzureRM API ratelimit
# TYPE azurerm_api_ratelimit gauge
azurerm_api_ratelimit{endpoint="management.azure.com",scope="subscription",subscriptionID="xxxx-xxxx-xxxx-xxxx",type="read"} 11998
# HELP azurerm_api_request AzureRM API requests
# TYPE azurerm_api_request histogram
azurerm_api_request_bucket{endpoint="management.azure.com",method="get",statusCode="200",le="0.1"} 0
azurerm_api_request_bucket{endpoint="management.azure.com",method="get",statusCode="200",le="0.25"} 0
azurerm_api_request_bucket{endpoint="management.azure.com",method="get",statusCode="200",le="0.5"} 0
azurerm_api_request_bucket{endpoint="management.azure.com",method="get",statusCode="200",le="1"} 2
azurerm_api_request_bucket{endpoint="management.azure.com",method="get",statusCode="200",le="2.5"} 2
azurerm_api_request_bucket{endpoint="management.azure.com",method="get",statusCode="200",le="5"} 2
azurerm_api_request_bucket{endpoint="management.azure.com",method="get",statusCode="200",le="10"} 2
azurerm_api_request_bucket{endpoint="management.azure.com",method="get",statusCode="200",le="30"} 2
azurerm_api_request_bucket{endpoint="management.azure.com",method="get",statusCode="200",le="60"} 2
azurerm_api_request_bucket{endpoint="management.azure.com",method="get",statusCode="200",le="+Inf"} 2
azurerm_api_request_sum{endpoint="management.azure.com",method="get",statusCode="200"} 1.606617
azurerm_api_request_count{endpoint="management.azure.com",method="get",statusCode="200"} 2
```

**Comment by mblaschke** [comment]
implemented with 8e2dd63cbe2418e03a78e516a90f98ff384df57e
that should give you good visibility of azure api calls

due to the limited validity `azurerm_api_ratelimit` are reset once `/metrics` is accessed

this also fixes duplicate `azurerm_ratelimit` (replaced by `azurerm_api_ratelimit`) metrics in prometheus server logs.

it will be available as `quay.io/webdevops/azure-metrics-exporter:main` in 1 or 2 hours.. the new build uses musl libc (alpine) instead of glibc and strips debug symbols.. so it's smaller

please share feedback :)

**Comment by mblaschke** [comment]
documentation is available here with the next version:
https://github.com/webdevops/azure-metrics-exporter#azuretracing-metrics

is now also controllable via env vars

**Comment by NissesSenap** [comment]
Sorry for not coming back to you @mblaschke. I haven't had time to update to the latest release so far but I hope to do that during the next week but you never know.
Thanks for taking the time to implement this feature.
