### ISSUE TITLE
Optimize ResourceGraph query to one API call for all subscriptions

### ISSUE THREAD

**Issue by j-sokol** [webdevops/azure-metrics-exporter#23]
Currently the query is run for each subscription separately (i.e https://github.com/webdevops/azure-metrics-exporter/blob/main/probe_metrics_resourcegraph.go#L64), so when a user has multiple subscriptions attached, they can reach the API ratelimit - which is currently 15 queries per 5 seconds:

https://docs.microsoft.com/en-us/azure/governance/resource-graph/concepts/guidance-for-throttled-requests#understand-throttling-headers

The Resource Graph API call can be run against multiple subscriptions, thus making the query way faster.

**Comment by grzesuav** [comment]
I think this issue should be closed as implemented
