### ISSUE TITLE
Is there any reason to separate these different exporters？

### ISSUE THREAD

**Issue by chrislinan** [webdevops/azure-metrics-exporter#25]
Hi, Thank you very much for your open source project, it is very helpful to me, I would like to ask why we need to differentiate between different exporters, for example, azure-metrics-exporter and azure-resourcemanager-exporter ? Can we combine these different exporters into one repo?

**Comment by mblaschke** [comment]
azure-metrics-exporter is publishing Azure resource metrics (only Azure Monitor API)

azure-resourcemanager-exporter is publishing general azure subscription metrics (resourcehealth, quotas, costs ...)

**Comment by chrislinan** [comment]
Thanks for your help.
