### ISSUE TITLE
Get subscription name as label

### ISSUE THREAD

**Issue by shanoor** [webdevops/azure-metrics-exporter#26]
Hi, this tool is great but is there a way to have the subscription name as a label on the metrics? The subscriptionID label is not very human-readable and usable in a dashboard.

**Comment by mblaschke** [comment]
I'm planing resource information in addition to metrics.

Will take some days.

**Comment by mblaschke** [comment]
this is still work in progress
the major priority is currently to migrate as much as possible to the new azure-sdk-for-go and then find a way to integrate such labels in a nice way

**Comment by Amrish-Sharma** [comment]
Hey @mblaschke,

this is pretty useful exporter, I am also looking for a way to relabel metrics for virtualnetwork gateways..

**Comment by jkroepke** [comment]
I'm also looking forward here. If the name is available as label, the values on Grafana Drop-Menu menu could be more readable.

**Comment by Amrish-Sharma** [comment]
Thanks @mblaschke !!
