### ISSUE TITLE
Off-topic: Helm charts discussions

### ISSUE THREAD

**Issue by jkroepke** [webdevops/azure-metrics-exporter#34]
Hi all,

sorry for being off-topic here. Slack invitation service doesn't work and twitter account seems stale. GitHub Discussions are disabled.

I would like to ask you, if you are interest into writing and hosting helm charts for the [webdevops](https://github.com/webdevops) projects like

* https://github.com/webdevops/azure-resourcegraph-exporter
* https://github.com/webdevops/azure-resourcemanager-exporter
* https://github.com/webdevops/azure-keyvault-exporter
* https://github.com/webdevops/azure-loganalytics-exporter

and more?

I suggest a dedicated helm-chart repository like https://github.com/jkroepke/helm-charts . If you are looking for additional maintainers, I can offer some help here.

**Comment by mblaschke** [comment]
The reason why there are no helm charts is the fact that i didn't had time for all this stuff.
I will ask my PO if I can push our helm charts into such a repository and I'm happy to accept help here.
Give me some days for discussions.

**Comment by jkroepke** [comment]
Hi @mblaschke, do you have an update for us?

Currently we are writing helm charts for some webdevops projects. Since I'm a fan of upstream first, I may able to contribute or help here.

Thanks

**Comment by mblaschke** [comment]
Ah, forgot to add:
I've got the approval but need to clean it up and make it more generic. Have some time in the next weeks to prepare it but that will be some work as it will not only affect the azure-metrics-exporter

**Comment by jkroepke** [comment]
Again my offer to assist here. Since I contribute to a lot helm charts, I can bring some best practices into it.

You can also take a took at https://github.com/jkroepke/helm-charts, if you need some inspiration for the github workflows, in terms of linting and automatic releasing.

**Comment by mblaschke** [comment]
thanks for the template, i was able to setup https://github.com/webdevops/helm-charts but it's in a very rough state and have to migrate the other charts as well.
might take some time
