### ISSUE TITLE
Exporter throwing error as missing environment variable for tenant id

### ISSUE THREAD

**Issue by krdineshbny** [webdevops/azure-metrics-exporter#35]
I trying to run this exporter to get the azure metrics.

Here is my prometheus yaml
`global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
- job_name: azure-metrics-keyvault
  honor_timestamps: true
  params:
    aggregation:
    - average
    - total
    filter:
    - resourceType eq 'Microsoft.KeyVault/vaults'
    interval:
    - PT15M
    metric:
    - Availability
    - ServiceApiHit
    - ServiceApiLatency
    name:
    - azure_metric_keyvault
    subscription:
    - xxxxxxxxxxxxxxxxxxxx
    timespan:
    - PT15M
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /probe/metrics/list
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - host1:8080`

and i have this in my start up script
`[azure]$ cat startup.sh
#!/bin/bash
# myscript
AZURE_CLIENT_ID="XXXX"
AZURE_TENANT_ID="YYYY"
AZURE_CLIENT_SECRET="ZZZZ"
./azure-metrics-exporter.linux.amd64
> ./myscript`

When i try to hit the exporter iam getting error stating tenant id missing , but i have passed it via startup script.
Please let me know if i need to pass the variables in a different way.

Below is the url prom is trying to get the metrics.
http://host1:8080/probe/metrics/list?aggregation=average&aggregation=total&filter=resourceType+eq+%27Microsoft.KeyVault%2Fvaults%27&interval=PT15M&metric=Availability&metric=ServiceApiHit&metric=ServiceApiLatency&name=azure_metric_keyvault&subscription=XXXXXXXXXXXXXXXXXXX&timespan=PT15M

This is the actual error iam getting on the exporter side
`./startup.sh
INFO[0000] starting azure-metrics-exporter v22.9.0 (ff038a4; go1.19.1; by webdevops.io)
INFO[0000] {"Logger":{"Debug":false,"Trace":false,"Json":false},"Azure":{"Environment":"AZUREPUBLICCLOUD","AdResourceUrl":null,"ServiceDiscovery":{"CacheDuration":1800000000000},"ResourceTags":["owner"]},"Metrics":{"Template":"{name}","Help":"Azure monitor insight metric"},"Prober":{"ConcurrencySubscription":5,"ConcurrencySubscriptionResource":10,"Cache":false},"Server":{"Bind":":8080","ReadTimeout":5000000000,"WriteTimeout":10000000000}}
INFO[0000] init Azure connection
INFO[0000] starting http server on :8080
ERRO[0056] servicediscovery failed: DefaultAzureCredential: failed to acquire a token.
Attempted credentials:
        EnvironmentCredential: missing environment variable AZURE_TENANT_ID
        ManagedIdentityCredential: IMDS token request timed out
        AzureCLICredential: Azure CLI not found on path  paramAggregation="[average total]" paramFilter="[resourceType eq 'Microsoft.KeyVault/vaults']" paramInterval="[PT15M]" paramMetric="[Availability ServiceApiHit ServiceApiLatency]" paramName="[azure_metric_keyvault]" paramSubscription="[XXXXXXXXXXXXXXXXXXXXXXXXX]" paramTimespan="[PT15M]" requestPath=/probe/metrics/list`

**Comment by mblaschke** [comment]
this error message is an error message from the azure-sdk-for-go.

are you sure the environment variables are active?

either do this:
```
#!/bin/bash
AZURE_CLIENT_ID="XXXX" \
AZURE_TENANT_ID="YYYY" \
AZURE_CLIENT_SECRET="ZZZZ" \
./azure-metrics-exporter.linux.amd64
```

or this:

```
#!/bin/bash
export AZURE_CLIENT_ID="XXXX"
export AZURE_TENANT_ID="YYYY"
export AZURE_CLIENT_SECRET="ZZZZ"
./azure-metrics-exporter.linux.amd64
```

or use the container image :)

**Comment by krdineshbny** [comment]
@mblaschke  thanks it worked
