### ISSUE TITLE
Exporter unable to get virtual network (vnet) metrics

### ISSUE THREAD

**Issue by shravanjnaidu** [webdevops/azure-metrics-exporter#38]
Hello Webdevops Team,

Great job on this exporter. It works great and the setup is much better compared to other exporters in the market. 

Issue: I'm facing an issue where I try to get metrics for MS Azure virtual network. But the exporter does not return anything. My metrics display fine on MS Azure portal but the exporter is unable to get them. 
I've tried using the /query UI to see the error message but it just returns 200 status code without any metrics. 
Every other resource type works but not vnet. 
I've pasted my configuration for vnet below. Is anybody else facing this issue? Any suggestions on how this can be resolved will be greatly appreciated. Thanks!

```    - job_name: webdevops-azure-metrics-vnet
        scrape_interval: 1m
        metrics_path: /probe/metrics/list
        params:
          name: ["mazure_metric_virtualnetworks"]
          template: ["{name}_{metric}_{aggregation}_{unit}"]
          subscription:
          - <my_subscription_id>
          resourceType: ["Microsoft.Network/virtualNetworks"]
          metric:
          - PingMeshProbesFailedPercent
          interval: ["PT1H"]
          timespan: ["PT1H"]
          aggregation:
          - average
          - total
          - count
        static_configs:
        - targets: ["<my_target>"]```

**Comment by mblaschke** [comment]
Do you get these metrics in Azure Portal?

**Comment by shravanjnaidu** [comment]
Yes, I do.

**Comment by mblaschke** [comment]
can you share a screenshot?

**Comment by shravanjnaidu** [comment]
[azure-metrics-exporter.pdf](https://github.com/webdevops/azure-metrics-exporter/files/10221272/azure-metrics-exporter.pdf)
Attached a screenshot. I hope it helps

**Comment by mblaschke** [comment]
I was talking about a screenshot from the Azure Portal showing your settings and the metric.

**Comment by mblaschke** [comment]
closed due to inactivity
