### ISSUE TITLE
aks Workload Identity support/New Release

### ISSUE THREAD

**Issue by timo-42** [webdevops/azure-metrics-exporter#49]
Hi

Azure moved away from aad pod identity to [Workload Identity](https://azure.github.io/azure-workload-identity/docs/topics/language-specific-examples/azure-identity-sdk.html). For this to work, the minimum needed version of  sdk/azidentity is `v1.3.0-beta.1`. Since the dependency bump in https://github.com/webdevops/azure-metrics-exporter/commit/b54491b59c986960f8c0c3e8608df74d62aeb9e3 this is already done.

My question would be: Do you have a date for the next release?

**Comment by mblaschke** [comment]
currently waiting for a stable release, Microsoft promised the release in the next days/weeks 🤞

**Comment by timo-42** [comment]
Azure did the release:
https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fazidentity%2Fv1.3.0

**Comment by mblaschke** [comment]
`23.6.0` released
