### ISSUE TITLE
How to get Azure resource Tag as part of Metric? and how to add Custom Tags in metric?

### ISSUE THREAD

**Issue by jitendrachopra** [webdevops/azure-metrics-exporter#5]

**Comment by mblaschke** [comment]
Fetch the resource list with tags with the `azure-resourcegraph-exporter` and join them in promql

**Comment by mblaschke** [comment]
Custom tags could be added on scraping using metrics relabel configs: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs

This can also be used with Prometheus operator.

**Comment by mblaschke** [comment]
closed -> no feedback
please reopen if this is still an issue
