### ISSUE TITLE
Traffic Manager Metrics No Endpoint Name

### ISSUE THREAD

**Issue by muralikanagala** [webdevops/azure-metrics-exporter#6]
Hi, We are using this exporter to monitor azure resources and it is really helpful.  While working on Azure traffic manager metrics I have noticed that the metrics does not contain the endpoint name information. So from the metrics we can not say which endpoint is up or down. Also, I did not find a config option to pull this information. Can I get some help here.
Thank you!

**Comment by mblaschke** [comment]
Do you use dimension support for such metrics?
Check the scrape job `azure-metrics-virtualNetworkGateways-connections` in README

**Comment by muralikanagala** [comment]
Thank you @mblaschke. I have updated the scrape config with metricFilter and it is working.
`    metricFilter:
    - EndpointName eq '*'`

**Comment by muralikanagala** [comment]
This is resolved.
