### ISSUE TITLE
Failure sending request: StatusCode=504 -- Original Error: context deadline exceeded"

### ISSUE THREAD

**Issue by gek0** [webdevops/azure-metrics-exporter#8]
Anyone else running into errors like this occasionally?
Seems like every 20-25 minutes or so, and subscription limits seem fine
Makes our Grafana non-usable per se due to frequent holes with no metrics
Running on 15 subscriptions at the moment

```
{
   "file":"prober.go:189",
   "func":"1",
   "level":"warning",
   "msg":"insights.MetricsClient#List: Failure sending request: StatusCode=504 -- Original Error: context deadline exceeded",
   "paramFilter":[
      "resourceType eq 'Microsoft.Network/loadBalancers'"
   ],
   "paramInterval":[
      "PT1M"
   ],
   "paramMetric":[
      "VipAvailability",
      "DipAvailability",
      "ByteCount",
      "PacketCount",
      "SYNCount",
      "SnatConnectionCount",
      "AllocatedSnatPorts",
      "UsedSnatPorts"
   ],
   "paramName":[
      "loadbalancer"
   ],
   "paramSubscription":[
      "XXXXXX,XXXXXX,XXXXXX,XXXXXX,XXXXXX,XXXXXX"
   ],
   "paramTimespan":[
      "PT1M"
   ],
   "requestPath":"/probe/metrics/list"
}
```

or even those which are more frequent - not sure how to filter a specific metric on a specific resource?

```
{
   "file":"prober.go:189",
   "func":"1",
   "level":"warning",
   "msg":"insights.MetricsClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"BadRequest\" Message=\"Failed to find metric configuration for provider: Microsoft.Network, resource Type: loadBalancers, metric: VipAvailability, Valid metrics: \"",
   "paramFilter":[
      "resourceType eq 'Microsoft.Network/loadBalancers'"
   ],
   "paramInterval":[
      "PT1M"
   ],
   "paramMetric":[
      "VipAvailability",
      "DipAvailability",
      "ByteCount",
      "PacketCount",
      "SYNCount",
      "SnatConnectionCount",
      "AllocatedSnatPorts",
      "UsedSnatPorts"
   ],
   "paramName":[
      "loadbalancer"
   ],
   "paramSubscription":[
      "XXXXXX,XXXXXX,XXXXXX,XXXXXX,XXXXXX,XXXXXX"
   ],
   "paramTimespan":[
      "PT1M"
   ],
   "requestPath":"/probe/metrics/list"
}
```

Using this on Prometheus job, should this be increased?
```
scrape_interval: 1m
scrape_timeout: 1m
...
      metric:
        - VipAvailability
        - DipAvailability
        - ByteCount
        - PacketCount
        - SYNCount
        - SnatConnectionCount
        - AllocatedSnatPorts
        - UsedSnatPorts
      interval: ["PT1M"]
      timespan: ["PT1M"]
```

Running with the following settings

> AZURE_ENVIRONMENT | AZUREPUBLICCLOUD
> CONCURRENCY_SUBSCRIPTION | 20
> CONCURRENCY_SUBSCRIPTION_RESOURCE | 200
> ENABLE_CACHING | true

**Comment by mblaschke** [comment]
which version are you using?
are you limiting resources of the metrics container (cpu request/limit)?
how many loadbalancers do you have per subscription? 
is there a reason why you set the concurrency of subscription resources to 200?
can you check the `scrape_duration_seconds` in Prometheus?

The exporter takes the scrape timeout from Prometheus and then terminates the context (which terminates the requetss). so if it takes longer than 60 seconds it will kill the current request.

if you have many loadbalancers in subscriptions maybe it's better to split the scrape configurations by subscription (one per subscription).

**Comment by gek0** [comment]
1. latest version of the exporter, built and running in Docker
2. no, running solo on 2cpu/4gb instances
3. 4-5 on most of them, 15-20 on one of them - but this will grow in the future
4. no. Not really sure how is that working? What would you recommend in this setup? Do mind that I'm planning to monitor storage accounts, network gateways, and such - different job but same exporter, would that be an overkill?
5. since caching enabled, always been very low. 1-2 seconds at max. for smaller jobs (less resources) it's under 400ms. for the un-cached hit, haven't noticed scrapes longer than 30 seconds

I did change the scrape and timeout interval to 2 min from 1 min yesterday and left it running for 12 hours, results do seem to improve drastically
![before](https://user-images.githubusercontent.com/8794964/118928288-4ebeb300-b943-11eb-9ab4-3cbff9543ee5.png)
![after](https://user-images.githubusercontent.com/8794964/118928290-4f574980-b943-11eb-8267-4870166ec969.png)

Not seeing 504s anymore, 400s yes, but this looks like it's just silently ignored and that metric not fetched - which is fine since it does not exists

I'm just interested in how well will it scale and will I need to split jobs per subscription or deploy separate exporters?
Our setup will grow for sure

**Comment by mblaschke** [comment]
3. that's totally fine, i don't see any issues here
4. the exporter tries to scrape 20 subscription at the same time and for each subscription it tries to scrape metrics from up to 200 resources at the same time. so in "worst case" it will run 4,000 (20*200) api requests at once. not sure if that could be too much. maybe keep the default and check if you still get 504s.
5. there are no more information in the logs when you got these 504? 🤔 

the exporter relies on the Azure API. if there are problems within Azure the exporter will also have them. So if Azure rolls out a buggy release you will notice that in your metrics as well.

I'm running the exporter for several big subscriptions without any issues so far with default concurrency settings and automatic scraping of subscriptions with the same call.

Let's keep the issue opened and I will have a look if I can see something suspicious. 

BTW: The next release will also include the resource id in the log message.

**Comment by gek0** [comment]
4. got it, reverted to 20 subs and 50 resources, a bit higher than default but for the last 24h I'm not seeing anymore 504s even with the 20/200 setting. Will further test and lower with time
5. unfortunately no, only "paramSubscription" with the list of set subscriptions is exposed and that's it - most of the message is visible up

great for exposing the resource ID!

**Comment by aobertyshev** [comment]
Greetings, I am also experiencing a similar problem.

I am running the exporter on `Debian 9` on `Standard B1s (1 vcpus, 1 GiB memory)` VM on Azure.

Here's my prometheus job:
```
  - job_name: azure_monitor
    scrape_interval: 5m
    metrics_path: /probe/metrics/list
    params:
      name: ["azure_metric_keyvault"]
      subscription:
      - <secret>
      filter: ["resourceType eq 'Microsoft.Compute/virtualMachines'"]
      metric:
      - CPU Credits Consumed
      interval: ["PT5M"]
      timespan: ["PT5M"]
      aggregation:
      - average
    static_configs:
    - targets:
      - <IP>:8080
```

Here's how Grafana dashboard looks like over 12h:
![image](https://user-images.githubusercontent.com/4324562/122373021-73697300-cf61-11eb-842d-3094dba13e51.png)

Just now I looked at the logs and saw a similar message to the one the TS has:
```
Jun 17 09:33:44 <hostname> azure-metrics-exporter[14085]: time="2021-06-17T09:33:44Z" level=warning msg="insights.MetricsClient#List: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded" paramAggregation="[average]" paramFilter="[resourceType eq 'Microsoft.Compute/virtualMachines']" paramInterval="[PT5M]" paramMetric="[CPU Credits Consumed]" paramSubscription="[<secret>]" paramTimespan="[PT5M]" requestPath=/probe/metrics/list
```
Judging from the quick googling, it seems to be  Azure's rate-limiting. Is there any potential change in the config that could alleviate this issue? Thank you in advance.

**Comment by mblaschke** [comment]
@aobertyshev 
have you enabled caching?

**Comment by mblaschke** [comment]
closing, feel free to reopen (or open a new issue) if you still have problems
